Repository IT-Contest/Back-End, pull requests merged in 2025-09, with the labels that each got.

#49 분석 관련 api, DB 수정
  src/main/java/ssuchaehwa/it_project/domain/analysis/application/ChatGPTService.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/api/PomodoroAnalysisController.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/api/PomodoroController.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroAnalysisService.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroAnalysisServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroService.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/domain/entity/Pomodoro.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/domain/entity/PomodoroStatus.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestAnalysisServiceImpl.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/ErrorStatus.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
  src/main/resources/application.yml
Labels: :star: feat

#50 퀘스트 분석 관련 api 수정
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestAnalysisServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/QuestOccurrenceRepository.java
Labels: :wrench: chore

#55 feat: 이용약관 기능 추가
  build.gradle
  src/main/java/ssuchaehwa/it_project/domain/analysis/application/CoachingServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/domain/entity/CoachingRecord.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/domain/repository/CoachingRecordRepository.java
  src/main/java/ssuchaehwa/it_project/domain/login/api/TestController.java
  src/main/java/ssuchaehwa/it_project/domain/login/application/LoginServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/domain/entity/Pomodoro.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/domain/repository/PomodoroRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/InvitedFriend.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/Party.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/PartyUser.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/Quest.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/InvitedFriendRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/PartyRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/PartyUserRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/QuestRepository.java
  src/main/java/ssuchaehwa/it_project/domain/user/api/UserController.java
  src/main/java/ssuchaehwa/it_project/domain/user/application/UserService.java
  src/main/java/ssuchaehwa/it_project/domain/user/application/UserServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/user/converter/UserConverter.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/Term.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/User.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/UserTerm.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/repository/TermRepository.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/repository/UserRepository.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/repository/UserTermRepository.java
  src/main/java/ssuchaehwa/it_project/domain/user/dto/UserRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/user/dto/UserResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/user/repository/UserRepository.java
  src/main/java/ssuchaehwa/it_project/global/config/security/SecurityConfig.java
  src/main/java/ssuchaehwa/it_project/global/config/security/auth/CustomUserDetailsService.java
  src/main/java/ssuchaehwa/it_project/global/config/security/auth/UserPrincipal.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/ErrorStatus.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__create_terms_table.sql
  src/main/resources/db/migration/V2__insert_initial_terms.sql
  src/main/resources/static/terms/privacy-policy-v1.html
  src/main/resources/static/terms/service-terms-v1.html
Labels: :star: feat

#58 분석화면 관련 api 수정
  .DS_Store
  src/main/java/ssuchaehwa/it_project/domain/analysis/application/CoachingServiceImpl.java
Labels: :wrench: chore

#60 chore: 파티 기능 코드 수정 및 수정, 삭제 추가
  src/main/java/ssuchaehwa/it_project/domain/model/enums/CompletionStatus.java
  src/main/java/ssuchaehwa/it_project/domain/quest/api/QuestRestController.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/Party.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/PartyUser.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/PartyRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/PartyUserRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/QuestRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/schedular/InviteCleanupScheduler.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestResponseDTO.java
  src/main/java/ssuchaehwa/it_project/global/config/security/SecurityConfig.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/ErrorStatus.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
  src/main/resources/static/simpson.jpg
Labels: :star: feat

#61 경험치 관련 api 수정
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/User.java
  src/main/resources/application.yml
Labels: :wrench: chore

#62 뽀모도로 qa 반영
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/api/PomodoroController.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroService.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/dto/PomodoroRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
Labels: :bug: fix

#63 chore: 퀘스트 파티 퀘스트 식별자 추가 및 코드 수정
  src/main/java/ssuchaehwa/it_project/domain/quest/api/QuestRestController.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/FcmService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestAnalysisServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/QuestOccurrence.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/enums/QuestSource.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/PartyUserRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/QuestOccurrenceRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestResponseDTO.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
  src/main/resources/application.yml
Labels: :wrench: chore

#64 qa 반영
  src/main/java/ssuchaehwa/it_project/domain/login/application/LoginServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/converter/PomodoroConverter.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/domain/entity/Pomodoro.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/dto/PomodoroResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/api/QuestRestController.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/user/api/UserController.java
  src/main/java/ssuchaehwa/it_project/domain/user/application/UserService.java
  src/main/java/ssuchaehwa/it_project/domain/user/application/UserServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/User.java
  src/main/java/ssuchaehwa/it_project/domain/user/dto/UserResponseDTO.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/ErrorStatus.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
Labels: :wrench: chore

#65 feat: 알림 추가
  .gitignore
  build.gradle
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/user/api/UserController.java
  src/main/java/ssuchaehwa/it_project/domain/user/application/UserService.java
  src/main/java/ssuchaehwa/it_project/domain/user/application/UserServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/User.java
  src/main/java/ssuchaehwa/it_project/domain/user/dto/UserRequestDTO.java
  src/main/java/ssuchaehwa/it_project/global/config/firebase/FireBaseConfig.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
  src/main/java/ssuchaehwa/it_project/global/service/FcmService.java
Labels: :star: feat

#66 chore: 개인 퀘스트, 파티 퀘스트 생성 및 완료 상태 api 수정
  src/main/java/ssuchaehwa/it_project/domain/login/application/LoginServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/login/dto/AuthResponseDto.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/Party.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/Quest.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/user/domain/entity/User.java
  src/main/java/ssuchaehwa/it_project/global/config/firebase/FireBaseConfig.java
Labels: :wrench: chore

#67 fix: 파티 조회 저장 로직 삭제
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
Labels: :bug: fix
