Repository IT-Contest/Back-End, pull requests merged in 2025-08, with the labels that each got.

#37 feat: 개인 퀘스트 수정, 삭제 api 구현, 관련 dto 수정
  src/main/java/ssuchaehwa/it_project/domain/quest/api/QuestRestController.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/entity/Quest.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/HashtagQuestRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/HashtagRepository.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/dto/QuestResponseDTO.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/ErrorStatus.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
Labels: :star: feat

#39 [Devops] add github actions yml file
  .github/workflows/deploy.yml
Labels: :construction_worker: devops

#40 [Devops] add github actions yml file
  .github/workflows/deploy.yml
Labels: :construction_worker: devops

#43 [chore] update setting
  scripts/profile.sh
Labels: :wrench: chore

#46 Feat/analysis - 분석 api 구현
  scripts/profile.sh
  src/main/java/ssuchaehwa/it_project/domain/analysis/api/CoachingController.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/application/ChatGPTService.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/application/CoachingService.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/application/CoachingServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/converter/CoachingConverter.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/domain/entity/CoachingRecord.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/domain/repository/CoachingRecordRepository.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/dto/AnalysisDataDTO.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/dto/CoachingRecordDTO.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/dto/CoachingRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/dto/CoachingResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/dto/SaveCoachingRequestDTO.java
  src/main/java/ssuchaehwa/it_project/domain/analysis/exception/CoachingException.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/api/PomodoroAnalysisController.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroAnalysisService.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/application/PomodoroAnalysisServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/converter/PomodoroConverter.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/domain/repository/PomodoroAnalysisRepository.java
  src/main/java/ssuchaehwa/it_project/domain/pomodoro/dto/PomodoroAnalysisResponseDTO.java
  src/main/java/ssuchaehwa/it_project/domain/quest/api/QuestAnalysisController.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestAnalysisService.java
  src/main/java/ssuchaehwa/it_project/domain/quest/application/QuestAnalysisServiceImpl.java
  src/main/java/ssuchaehwa/it_project/domain/quest/converter/QuestConverter.java
  src/main/java/ssuchaehwa/it_project/domain/quest/domain/repository/QuestAnalysisRepository.java
  src/main/java/ssuchaehwa/it_project/global/error/code/status/SuccessStatus.java
Labels: :star: feat

#48 [Chore] correct openAI Setting
  src/main/resources/application.yml
Labels: :wrench: chore
